import type { Metadata } from "next";

import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The blog - Este é um blog com next.js",
    template: "%s | The blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          {children}
          <footer className="text-6xl text-slate-800 font-bold py-8 text-center">
            footer
          </footer>
        </Container>
      </body>
    </html>
  );
}
